package com.example.sjj.help4reword;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.sjj.help4reword.MissionInfo;
import com.example.sjj.help4reword.UserInfo;

import com.example.sjj.help4reword.MissionInfoDao;
import com.example.sjj.help4reword.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig missionInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final MissionInfoDao missionInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        missionInfoDaoConfig = daoConfigMap.get(MissionInfoDao.class).clone();
        missionInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        missionInfoDao = new MissionInfoDao(missionInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(MissionInfo.class, missionInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        missionInfoDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
    }

    public MissionInfoDao getMissionInfoDao() {
        return missionInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
